In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
from torch import nn
import numpy as np

In [15]:
class LSTMNERTagger(nn.Module):
    def __init__(
        self, 
        embedding_dim: int,
        vocab_size: int, 
        hidden_units: int):
        super().__init__()
        self.embed = nn.Embedding(
            num_embeddings=vocab_size,
            embedding_dim=embedding_dim)
        self.lstm = nn.LSTM(
            input_size=embedding_dim, 
            hidden_size=hidden_units, 
            batch_first=True)
        
    def forward(self, x):
        x = self.embed(x)
        x = self.lstm(x)
        return x

In [16]:
batch_size = 2
embedding_dim = 3
vocab_size = 5
hidden_units = 7
seq_length = 9
# x = torch.randn(,)

lstm = LSTMNERTagger(embedding_dim=embedding_dim, vocab_size=vocab_size, hidden_units=hidden_units)


In [34]:
rng = np.random.default_rng(42)
X = rng.choice(vocab_size, size=(batch_size, seq_length))

y = rng.choice(vocab_size, size=vocab_size)
Y = [[y[i] for i in x] for x in X]

X = torch.tensor(X)
Y = torch.tensor(Y)

X, Y

(tensor([[0, 3, 3, 2, 2, 4, 0, 3, 1],
         [0, 2, 4, 3, 3, 3, 3, 2, 0]]),
 tensor([[4, 1, 1, 2, 2, 0, 4, 1, 2],
         [4, 2, 0, 1, 1, 1, 1, 2, 4]]))

tensor([[0, 3, 3, 2, 2, 4, 0, 3, 1],
        [0, 2, 4, 3, 3, 3, 3, 2, 0]])

In [33]:
Y

tensor([[4, 1, 1, 2, 2, 0, 4, 1, 2],
        [4, 2, 0, 1, 1, 1, 1, 2, 4]])

In [27]:
y

4

In [22]:
output, (h_n, c_n) = lstm(x)

In [23]:
output.shape, h_n.shape, c_n.shape

(torch.Size([2, 9, 7]), torch.Size([1, 2, 7]), torch.Size([1, 2, 7]))